CREATE DATABASE IF NOT EXISTS EVENTS;
USE EVENTS;

CREATE TABLE IF NOT EXISTS EVENT(
    EVENTID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    EVENTNAME VARCHAR(100) NOT NULL,
    EVENTDATE DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS TICKET(
    TICKETID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    TICKETPRICE INT NOT NULL,
    TICKETNUM INT NOT NULL,
    EVENTID INT NOT NULL,
    FOREIGN KEY (EVENTID) REFERENCES EVENT(EVENTID)
);

CREATE TABLE IF NOT EXISTS CUSTOMER(
    CUSTOMERID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    CUSTOMERNAME VARCHAR(100) NOT NULL,
    CUSTOMERCASH INT NOT NULL,
    TICKETID INT NOT NULL,
    FOREIGN KEY (TICKETID) REFERENCES TICKET(TICKETID)
);

INSERT INTO EVENT (EVENTNAME, EVENTDATE)
VALUES
    ('Concert A', '2024-07-15'),
    ('Conference B', '2024-08-20'),
    ('Exhibition C', '2024-09-10');

INSERT INTO TICKET (TICKETPRICE, TICKETNUM, EVENTID)
VALUES
    (50, 100, 1),
    (30, 50, 2),
    (20, 200, 3);

INSERT INTO CUSTOMER (CUSTOMERNAME, CUSTOMERCASH, TICKETID)
VALUES
    ('John Doe', 500, 1),
    ('Jane Smith', 300, 2);

-- update ticket 
-- set TICKETPRICE = 30 
-- where TICKETID = 1

-- select * from ticket t 
-- order by TICKETPRICE ASC

-- SELECT * FROM ticket t 
-- WHERE TICKETPRICE  BETWEEN 10 AND 25;